Repository Rakesh9100/CalcDiverse, pull requests merged in 2024-01, with the labels that each got.

#52 GPA Calculator
  Calculators/GPA-Calculator/README.md
  Calculators/GPA-Calculator/index.html
  Calculators/GPA-Calculator/script.js
  Calculators/GPA-Calculator/style.css
  index.html
Labels: Completed 🥳, SWOC S4, Hard

#62 Length Convertor Added
  Calculators/Length-Convertor/Length.css
  Calculators/Length-Convertor/Length.html
  Calculators/Length-Convertor/Length.js
  Calculators/Length-Convertor/README.md
  index.html
Labels: Completed 🥳, SWOC S4, Medium

#142 BMI Calculator UI Updated
  Calculators/BMI-Calculator/BMI-Calculator.css
  Calculators/BMI-Calculator/BMI-Calculator.html
  Calculators/BMI-Calculator/BMI-Calculator.js
  Calculators/BMI-Calculator/README.md
Labels: Completed 🥳, SWOC S4, Medium

#204 Added Rectangular to polar calculator
  Calculators/Rectangular-To-Polar-Calculator/README.md
  Calculators/Rectangular-To-Polar-Calculator/index.html
  Calculators/Rectangular-To-Polar-Calculator/script.js
  Calculators/Rectangular-To-Polar-Calculator/style.css
  index.html
Labels: question 🤔

#211 Added matrix calculator
  Calculators/Matrix-Calculator/README.md
  Calculators/Matrix-Calculator/matrix.css
  Calculators/Matrix-Calculator/matrix.html
  Calculators/Matrix-Calculator/matrix.js
  index.html
Labels: question 🤔

#217 Added Percentage to Fraction Calculator
  Calculators/Percentage-To-Fraction-Calculator/Readme.md
  Calculators/Percentage-To-Fraction-Calculator/index.html
  Calculators/Percentage-To-Fraction-Calculator/script.js
  Calculators/Percentage-To-Fraction-Calculator/style.css
  index.html
Labels: question 🤔

#218 Linear equation Calculator
  Calculators/Linear-Equation-Calculator/assets/Screenshot (181).png
  Calculators/Linear-Equation-Calculator/assets/Screenshot (182).png
  Calculators/Linear-Equation-Calculator/index.html
  Calculators/Linear-Equation-Calculator/readme.md
  Calculators/Linear-Equation-Calculator/script.js
  Calculators/Linear-Equation-Calculator/style.css
  index.html
Labels: question 🤔

#196 Added quadratic calculator
  Calculators/Quadratic-Calculator/assets/Screenshot quadratic-1.png
  Calculators/Quadratic-Calculator/assets/Screenshot quadratic-2.png
  Calculators/Quadratic-Calculator/index.html
  Calculators/Quadratic-Calculator/readme.md
  Calculators/Quadratic-Calculator/script.js
  Calculators/Quadratic-Calculator/style.css
  index.html
Labels: question 🤔

#215 Added Basic Calculator
  Calculators/Basic-Calculator/README.md
  Calculators/Basic-Calculator/index.html
  Calculators/Basic-Calculator/script.js
  Calculators/Basic-Calculator/style.css
  index.html
Labels: question 🤔

#229 Enhance the Contributors Section
  assets/Contributors/Contibutor.js
  assets/Contributors/Contributor.html
  assets/Contributors/style.css
  index.html
Labels: question 🤔

#231 Added AP and GP Calculator
  Calculators/Arithmetic-Progression-Calculator/README.md
  Calculators/Arithmetic-Progression-Calculator/ap-calc.png
  Calculators/Arithmetic-Progression-Calculator/index.html
  Calculators/Arithmetic-Progression-Calculator/script.js
  Calculators/Arithmetic-Progression-Calculator/style.css
  Calculators/Geometric-Progression-Calculator/README.md
  Calculators/Geometric-Progression-Calculator/gp-calc.png
  Calculators/Geometric-Progression-Calculator/index.html
  Calculators/Geometric-Progression-Calculator/script.js
  Calculators/Geometric-Progression-Calculator/style.css
  index.html
Labels: question 🤔

#292 Harmonic Progression Calculator Added
  Calculators/Harmonic-Progression-Calculator/README.md
  Calculators/Harmonic-Progression-Calculator/index.html
  Calculators/Harmonic-Progression-Calculator/script.js
  Calculators/Harmonic-Progression-Calculator/style.css
  index.html
Labels: question 🤔

#262 Number System Calculator Added
  Calculators/Number-System-Calculator/Number-System.css
  Calculators/Number-System-Calculator/Number-System.html
  Calculators/Number-System-Calculator/Number-System.js
  Calculators/Number-System-Calculator/README.md
  index.html
Labels: question 🤔

#300 Word Count Calculator Added
  Calculators/Word-Count-Calculator/index.html
  Calculators/Word-Count-Calculator/script.js
  Calculators/Word-Count-Calculator/styles.css
  index.html
Labels: question 🤔

#310 Added Love Calculator
  Calculators/Love-Calculator/README.md
  Calculators/Love-Calculator/index.html
  Calculators/Love-Calculator/script.js
  Calculators/Love-Calculator/styles.css
  index.html
Labels: question 🤔

#316 Added Pregnancy Due Date Calculator
  Calculators/Pregnancy-Due-Date-Calculator/README.md
  Calculators/Pregnancy-Due-Date-Calculator/index.html
  Calculators/Pregnancy-Due-Date-Calculator/script.js
  Calculators/Pregnancy-Due-Date-Calculator/styles.css
  index.html
Labels: question 🤔

#338 Added Intelligence Calculator
  Calculators/Intelligence-Calculator/README.md
  Calculators/Intelligence-Calculator/index.html
  Calculators/Intelligence-Calculator/script.js
  Calculators/Intelligence-Calculator/styles.css
  index.html
Labels: question 🤔

#336 Ellipse and Hyperbola Calculator Added
  Calculators/Ellipse-And-Hyperbola-Calculator/Image/Ellipse-And-Hyperbola-Cal.png
  Calculators/Ellipse-And-Hyperbola-Calculator/README.md
  Calculators/Ellipse-And-Hyperbola-Calculator/index.html
  Calculators/Ellipse-And-Hyperbola-Calculator/script.js
  Calculators/Ellipse-And-Hyperbola-Calculator/styles.css
  index.html
Labels: question 🤔

#315 Added Clothing Size Calculator
  Calculators/Clothing-Size-Calculator/domManager.js
  Calculators/Clothing-Size-Calculator/index.html
  Calculators/Clothing-Size-Calculator/readme.md
  Calculators/Clothing-Size-Calculator/script.js
  Calculators/Clothing-Size-Calculator/size_mapping.json
  Calculators/Clothing-Size-Calculator/styles.css
  index.html
Labels: question 🤔

#343 Added Keyboard Input for User Values in Basic Calculator
  Calculators/Basic-Calculator/script.js
Labels: question 🤔

#354 Added Systematic Investment Plan Calculator
  Calculators/Systematic-Investment-Plan-Calculator/Readme.md
  Calculators/Systematic-Investment-Plan-Calculator/image.png
  Calculators/Systematic-Investment-Plan-Calculator/index.html
  Calculators/Systematic-Investment-Plan-Calculator/script.js
  Calculators/Systematic-Investment-Plan-Calculator/style.css
  index.html
Labels: question 🤔

#350 Added Short URL Calculator
  Calculators/Short-URL-Calculator/App.js
  Calculators/Short-URL-Calculator/Readme.md
  Calculators/Short-URL-Calculator/Style.css
  Calculators/Short-URL-Calculator/copy.js
  Calculators/Short-URL-Calculator/index.html
  index.html
Labels: question 🤔

#356 Handled NaN in Trigonometric Calculator
  Calculators/Trigonometric-Calculator/script.js
Labels: question 🤔

#377 Added Net Salary Calculator
  Calculators/Net-Salary-Calculator/Readme.md
  Calculators/Net-Salary-Calculator/Screenshot.png
  Calculators/Net-Salary-Calculator/index.html
  Calculators/Net-Salary-Calculator/script.js
  Calculators/Net-Salary-Calculator/style.css
  index.html
Labels: question 🤔

#379 Added Conductivity and Resistivity Calculator
  Calculators/Conductivity-And-Resistivity-Calculator/image.png
  Calculators/Conductivity-And-Resistivity-Calculator/index.html
  Calculators/Conductivity-And-Resistivity-Calculator/readme.md
  Calculators/Conductivity-And-Resistivity-Calculator/script.js
  Calculators/Conductivity-And-Resistivity-Calculator/styles.css
  index.html
Labels: question 🤔

#378 Added Calorie Burnt Calculator
  Calculators/Calorie-Burnt-Calculator/Readme.md
  Calculators/Calorie-Burnt-Calculator/index.html
  Calculators/Calorie-Burnt-Calculator/script.js
  Calculators/Calorie-Burnt-Calculator/styles.css
  index.html
Labels: question 🤔

#395 Added Baye's Theorem Calculator
  Calculators/Baye's-Theorem-Calculator/README.md
  Calculators/Baye's-Theorem-Calculator/index.html
  Calculators/Baye's-Theorem-Calculator/script.js
  Calculators/Baye's-Theorem-Calculator/styles.css
  index.html
Labels: question 🤔

#361 UI Enhanced for the Color Code Calculator
  Calculators/4-Band-Resistance-Calculator/index.html
  Calculators/Color-Code-Calculator/index.html
  Calculators/Color-Code-Calculator/script.js
  Calculators/Color-Code-Calculator/style.css
Labels: question 🤔

#365 Added Environmental Calculator
  Calculators/Environmental-Calculator/README.md
  Calculators/Environmental-Calculator/index.html
  Calculators/Environmental-Calculator/script.js
  Calculators/Environmental-Calculator/style.css
  index.html
Labels: question 🤔

#422 Added Logo in Navbar
  index.html
  style.css
Labels: question 🤔

#436 UI appearance of every calculator
  style.css
Labels: question 🤔

#446 Added Expenditure And Savings Calculator
  Calculators/Expenditure-And-Savings-Calculator/image.png
  Calculators/Expenditure-And-Savings-Calculator/index.html
  Calculators/Expenditure-And-Savings-Calculator/readme.md
  index.html
Labels: question 🤔

#454 Added voice command Search bar
  script.js
  style.css
Labels: question 🤔

#460 Added Thala for a Reason Calculator
  Calculators/Thala-For-A-Reason-Calculator/README.md
  Calculators/Thala-For-A-Reason-Calculator/index.html
  Calculators/Thala-For-A-Reason-Calculator/screenshot.png
  Calculators/Thala-For-A-Reason-Calculator/script.js
  Calculators/Thala-For-A-Reason-Calculator/style.css
  Calculators/Thala-For-A-Reason-Calculator/thala.jpg
  index.html
Labels: question 🤔

#463 Added Cricket Calculator
  Calculators/Cricket-Calculator/README.md
  Calculators/Cricket-Calculator/index.html
  Calculators/Cricket-Calculator/script.js
  Calculators/Cricket-Calculator/style.css
  index.html
Labels: question 🤔

#477 Added Date and Time Calculator
  Calculators/Date-Time-Calculator/index.html
  Calculators/Date-Time-Calculator/index.js
  Calculators/Date-Time-Calculator/readme.md
  Calculators/Date-Time-Calculator/style.css
  index.html
Labels: question 🤔, status: standby ✊

#478 Twitter Facebook links fixed in footer
  assets/contact/contact.html
  assets/contributors/contributor.html
  index.html
Labels: question 🤔

#482 Added Equivalent Resistance Calculator
  Calculators/Equivalent-Resistance-Calculator/Readme.md
  Calculators/Equivalent-Resistance-Calculator/index.html
  index.html
Labels: question 🤔

#490 Added Centripetal Force Calculator
  Calculators/Centripetal-Force-Calculator/README.md
  Calculators/Centripetal-Force-Calculator/cfimage.png
  Calculators/Centripetal-Force-Calculator/index.html
  Calculators/Centripetal-Force-Calculator/script.js
  Calculators/Centripetal-Force-Calculator/style.css
  index.html
Labels: question 🤔

#503 Enhanced 2D Shapes Calculator and Color Code Calculator
  Calculators/2D-Shapes-Calculator/2D-Shapes-Calcnew.css
  Calculators/2D-Shapes-Calculator/2D-Shapes-Calculator.html
  Calculators/2D-Shapes-Calculator/2Dshapes.jpg
  Calculators/Color-Code-Calculator/colourcode.jpg
  Calculators/Color-Code-Calculator/index.html
  Calculators/Color-Code-Calculator/style.css
Labels: question 🤔
